language: node_js
env:
  global:
    - NPM_CONFIG_LOGLEVEL=warn
before_install:
  - npm install -g greenkeeper-lockfile
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm test
after_script:
  - greenkeeper-lockfile-upload
cache:
  directories:
    - node_modules
# This causes builds for merges and direct pushes to master.
# Other branches are pull requests and build are triggered via the
# pull request hook
branches:
  only:
    - master
    - /^greenkeeper/.*$/
