name: CI

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set the correct npm version
        run: nvm install && nvm use

      - name: Install dependencies from npm
        run: |
          nvm use
          npm ci

      - name: Build & Test
        run: |
          nvm use
          npm test